name: Build Angular App

on:
  push:
    branches: [ main ]

jobs:
  build-angular-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        working-directory: angular6-realworld-highly-scalable-application
        run: npm ci

      - name: Build Angular app
        working-directory: angular6-realworld-highly-scalable-application
        run: npm run build
