jobs:
  build-angular-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm install
        working-directory: angular6-realworld-highly-scalable-application

      - name: Build Angular app
        run: npm run build
        working-directory: angular6-realworld-highly-scalable-application
